### ISSUE TITLE
TODO-List

### ISSUE THREAD

**Issue by SuperSaiyajinStackZ** [Universal-Team/3DEins#5]
- [ ] Finish 3DEins core classes.

- [x] Add Computer Opponent.

- [ ] Add Local Multiplayer.

- [ ] Add Online(?) Multiplayer. (I may need help on that likely.)

- [ ] Add Fancy Effects. (Like dropping a card for example.)

- [ ] Better Card Graphics. (The current one look bad.)

**Comment by SuperSaiyajinStackZ** [comment]
Currently in progress:

- [ ] Finish 3DEins core classes.

**Comment by SuperSaiyajinStackZ** [comment]
The TODO List will Change now completely. This is the new TODO list now:

- [x] Initial [3DEins-Core](https://github.com/SuperSaiyajinStackZ/3DEins-Core) implementation into 3DEins. (This is currently in Progress and should be done tomorrow if everything is going well.)

- [ ] Maybe UI Style changes.

- [ ] Fixing 3DEins Cards. (They look weird currently.)

- [ ] More TODO's coming soon...

**Comment by SuperSaiyajinStackZ** [comment]
Initial 3DEins-Core implementation is done. Tho, for now only 2 Player work now, 3-4 Player is still WIP.

**Comment by SuperSaiyajinStackZ** [comment]
4 Player Functionality got added & big cleanup as well for the GameScreen. 

Known Issue:
- `std::random_device` seems to generate the same CardDeck on every 3DEins start, which makes it really predictable for the game and destroys possibly fun. TODO: Find a better way. Maybe switch back to srand() or so? Not sure yet.

**Comment by ghost** [comment]
Gotta update this here:

*Planned things:*
- Working on DSEins. (The DS(i) variant of 3DEins.) This version uses 3DEins-Core as well, cause it works pretty well. Initial work has already be worked on and is on the DSEins branch. You will be able to find Releases to both on this repository, since it's not worth to make a `DSEins` repo.

**Comment by ghost** [comment]
The DSEins version is almost initially done now. Just a few things needs to be fixed now.

**Comment by ghost** [comment]
DSEins is now "initially" done and merged to master.

**Comment by ghost** [comment]
An AI for 3DEins & DSEins has been fully implemented with this commit here. https://github.com/Universal-Team/3DEins/commit/b8a3e005f753b2ee4910bc164780dc6f201e77e6

There are 3 or 4 commits which include AI stuff.
